<h1><b>Numpy</b></h1>

In [4]:
import numpy as np

In [4]:
my_list = np.array([1,2,3])

In [5]:
print(my_list)

[1 2 3]


In [7]:
my_mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
print(my_mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(type(my_mat))

<class 'numpy.ndarray'>


In [9]:
for i in my_mat:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9


In [13]:
print(np.arange(1,10,2))

[1 3 5 7 9]


In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [19]:
np.random.rand(5)

array([0.10617695, 0.2866912 , 0.35855373, 0.86162813, 0.83745798])

In [21]:
np.random.randn(5,5)

array([[-0.86963639, -1.43408745, -0.09662395, -1.2423771 , -1.34483591],
       [ 0.36774954, -0.49458975,  1.27806316,  0.56797253, -0.2406744 ],
       [ 0.50562372,  0.70240649, -0.85364625, -1.38813439, -1.68122328],
       [-0.39848967,  0.56519561,  1.10037478, -0.14533988, -0.81969717],
       [ 0.83979823, -0.84138672,  0.57159311,  0.20381997, -0.08609274]])

In [22]:
np.random.randint(60,100)

92

In [29]:
arr = np.random.randint(1,100,10)

In [30]:
arr.reshape(5,2)

array([[84, 32],
       [41, 55],
       [39, 76],
       [13, 98],
       [76, 68]], dtype=int32)

In [31]:
arr.max()

np.int32(98)

In [32]:
arr.min()

np.int32(13)

In [33]:
arr.shape

(10,)

In [35]:
arr.dtype

dtype('int32')

In [39]:
arr = np.array([1,2,3,4,5])

In [40]:
print(arr[3:])

[4 5]


In [41]:
arr[:] = 99

In [42]:
print(arr)

[99 99 99 99 99]


In [43]:
new_arr = arr.copy()

In [44]:
new_arr

array([99, 99, 99, 99, 99])

In [5]:
my_mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
print(my_mat[1][2])

6


In [7]:
print(my_mat[1:][1:])

[[7 8 9]]


In [19]:
to_be_bool_arr = np.arange(1,10)

In [10]:
bool_arr = to_be_bool_arr > 5

In [11]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True])

In [12]:
np.array(to_be_bool_arr > 5)

array([False, False, False, False, False,  True,  True,  True,  True])

In [17]:
to_be_bool_arr[bool_arr]

array([6, 7, 8, 9])

In [20]:
to_be_bool_arr[to_be_bool_arr < 3]

array([1, 2])

In [23]:
arr = np.arange(50).reshape(5,10)

In [24]:
arr 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [26]:
arr[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [27]:
arr = np.arange(1,10)

In [28]:
arr + arr 

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
arr - arr 

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
arr * arr 

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [31]:
arr / arr 

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
arr - 111 

array([-110, -109, -108, -107, -106, -105, -104, -103, -102])

In [33]:
1 / arr 

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111])

In [34]:
arr * 2 

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [35]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [36]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [38]:
print(np.max(arr))

9


In [41]:
arr.max()

np.int64(9)